create folders for cryptocurrency site relate #1
GSG-CF05/CryptocurrencySite pull request #2
Opened 2022-03-16 23:37 UTC by ayaenshasy2002

2022-03-17 17:56 UTC, ShbairAli submitted a review, later dismissed

2022-03-17 20:05 UTC, husamkamal requested changes
Add All file structure

2022-03-18 00:42 UTC, Mai-Elhajeen submitted a review, later dismissed

2022-03-18 00:48 UTC, ShbairAli submitted a review, later dismissed

2022-03-18 00:49 UTC, omaraburabie3 submitted a review, later dismissed

2022-03-18 19:38 UTC, Mai-Elhajeen approved these changes

2022-03-18 19:38 UTC, husamkamal approved these changes

2022-03-18 19:39 UTC, ShbairAli approved these changes
well done Aya

2022-03-18 19:39 UTC, Mai-Elhajeen approved these changes

2022-03-18 19:39 UTC, omaraburabie3 approved these changes
**Great!**

2022-03-18 19:40 UTC, omaraburabie3 approved these changes

2022-03-18 19:41 UTC, Mai-Elhajeen approved these changes

2022-03-18 19:44 UTC, merged