edit about page relate #29
GSG-CF05/CryptocurrencySite pull request #30
Opened 2022-03-22 10:56 UTC by ayaenshasy2002

2022-03-22 11:00 UTC, ShbairAli submitted a review, later dismissed

2022-03-22 21:09 UTC, Mai-Elhajeen submitted a review, later dismissed

2022-03-23 11:20 UTC, husamkamal requested changes
There is no dot in the href for linking between pages

2022-03-23 17:02 UTC, ShbairAli approved these changes

2022-03-23 17:03 UTC, merged